server:
  port: 8080
  shutdown: graceful #Wait if it has any action
  forward-headers-strategy: framework
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles:
    active: TEST
  datasource:
    url: jdbc:postgresql://localhost:5433/security
    username: postgres
    password: 1273
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
jwt:
  token:
    secret: jwtjavasamo
    validity: 864000000
springdoc:
  swagger-ui:
    path: /v1/swagger/index.html
  api-docs:
    path: /v1/swagger/api-docs
lawyer: https://api.e-advokat.uz/api/v.1/getInfo/lawyerList